/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:4ad10353-0ec5-473d-b98c-470dd55cd71b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_sEDoOTnfj",
    "aws_user_pools_web_client_id": "4vj3b0b4c16dfrn369fj9j2ris",
    "oauth": {}
};


export default awsmobile;
